# -*- coding: utf-8 -*-
"""Data Visualisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14xeeWDERbJ8cWX2ThcMyAFPEj0UuLgC4
"""



"""Visualization

Visualization

###Matplot lib

```
# This is formatted as code
```
"""

import numpy as np
import matplotlib.pyplot as plt

years=[1960,1970,1980,1990,2000,2010,2016]
pop = [21.91,28.51,38.67,56.23,66.13,74.57,80.28]



"""## line plot"""



"""with this function we can draw a line with x and y"""

plt.plot(years,pop)
plt.show()

plt.figure(figsize=(9,6),dpi=100)
plt.plot(years,pop,color="green")
plt.xlabel('Year')
plt.ylabel("Population")
plt.title("Country Population")
plt.yticks([21.91,28.51,38.67,56.23,66.13,74.57,80.28],['21M','28M','38M','56M','66M','74M','80M'])
plt.show()



"""###Scatter plot"""

plt.scatter(years,pop)
plt.show

popsize = np.array(pop)*4
popsize
plt.scatter(years,pop,s=popsize,color='green')
plt.xlabel('Year')
plt.ylabel('Population')
plt.title('Country Population')
plt.yticks([21.91,28.51,38.67,56.23,66.13,74.57,80.28],['21M','28M','38M','56M','66M','74M','80M'])
plt.show()



"""###Bar Chat"""

t1 = [1,3,4,5,6,7,9]
tt1 = [4,7,10,4,7,8,3]

t2= [2,4,6,8,10]
tt2=[5,6,2,6,2]
plt.bar(t1,tt1,label="Blue Bar",color='b')
plt.bar(t2,tt2,label="Green Bar",color='g')

plt.xlabel('bar number')
plt.ylabel('bar height')
plt.title('Ber chart example')
plt.legend()
plt.show



"""###Histogram Plot"""



"""### Histogram helps to get idea about Distribution"""

cit_name=['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz']

city_pop=[7153309,2307177,1947164, 1448075, 1424641, 1249942]
plt.hist(city_pop)
plt.xlabel('Population')
plt.ylabel('City number')

plt.show



"""##Pie Chat"""

plt.pie(city_pop,labels=cit_name,autopct = '%1.1f%%')
plt.show()

height = [5.8, 12.2, 21.5]
bars = ('Gruber& Narayanan(2019)', 'Konig & conway (2016)', 'Conway et.al (2017)')

plt.barh(bars,height)
plt.xlabel('References')
plt.ylabel(' distance(KM)')
plt.title("Average daily distance(KM)")

plt.show()







"""###SeaBorn"""



"""seabon isbased top of matplotlib

work with Pandas Data Structuren. It has more adv grapgic graphic tools
"""

import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

smartphone =pd.read_csv("/content/drive/MyDrive/Colab Notebooks/data set/smartphones.csv")
smartphone



"""##Swarm plot"""

plt.figure(figsize=(13,8))
sb.swarmplot(x="OS",y="Capacity",data=smartphone,hue="OS",size=20)
plt.show()



smartphone =pd.read_csv("/content/drive/MyDrive/Colab Notebooks/data set/smartphones.csv")
smartphone

sb.boxplot(x='Company',y='Ram',data=smartphone)
plt.show()

